module.exports = {
	// Core
	PRODUCT_WORKPLACE: 'workplace',
	PRODUCT_WWW: 'www',
	SETTINGS_STORAGE: 'settings.json',

	// Notifications
	DOCK_COUNT: 'dock-count',
	NOTIFICATION_COUNT: 'notification-count',
	NEW_MESSAGE_NOTIFICATION: 'NEW_MESSAGE_NOTIFICATION',

	// Navigation
	NEW_CONVERSATION: 'new-conversation',
	NEXT_CONVERSATION: 'next-conversation',
	PREV_CONVERSATION: 'prev-conversation',
	JUMP_TO_CONVERATION: 'JUMP_TO_CONVERATION',
	JUMP_TO_CONVERATION_BY_IMAGE_NAME: 'JUMP_TO_CONVERATION_BY_IMAGE_NAME',
	
	SHOW_SETTINGS: 'SHOW_SETTINGS',
	SHOW_MESSAGE_LIST_INBOX: 'SHOW_MESSAGE_LIST_INBOX',
	SHOW_MESSAGE_LIST_ACTIVE_CONTACTS: 'SHOW_MESSAGE_LIST_ACTIVE_CONTACTS',
	SHOW_MESSAGE_LIST_MESSAGE_REQUESTS: 'SHOW_MESSAGE_LIST_MESSAGE_REQUESTS',
	SHOW_MESSAGE_LIST_ARCHIVED_THREADS: 'SHOW_MESSAGE_LIST_ARCHIVED_THREADS',

	// Misc
	TOUCH_BAR: 'TOUCH_BAR',
};
