module.exports = {
	// Core
	SETTINGS_STORAGE: 'settings.json',

	// Notifications
	DOCK_COUNT: 'dock-count',
	NOTIFICATION_COUNT: 'notification-count',
	NEW_MESSAGE_NOTIFICATION: 'NEW_MESSAGE_NOTIFICATION',

	// Navigation
	NEW_CONVERSATION: 'new-conversation',
	NEXT_CONVERSATION: 'next-conversation',
	PREV_CONVERSATION: 'prev-conversation',
	JUMP_TO_CONVERSATION: 'JUMP_TO_CONVERSATION',
	JUMP_TO_CONVERSATION_BY_IMAGE_NAME: 'JUMP_TO_CONVERSATION_BY_IMAGE_NAME',
	
	OPEN_MESSENGER: 'open-window',
	SHOW_MESSENGER_SETTINGS: 'SHOW_MESSENGER_SETTINGS',
	SHOW_MESSAGE_LIST_INBOX: 'SHOW_MESSAGE_LIST_INBOX',
	SHOW_MESSAGE_LIST_ACTIVE_CONTACTS: 'SHOW_MESSAGE_LIST_ACTIVE_CONTACTS',
	SHOW_MESSAGE_LIST_MESSAGE_REQUESTS: 'SHOW_MESSAGE_LIST_MESSAGE_REQUESTS',
	SHOW_MESSAGE_LIST_HIDDEN_CHATS: 'SHOW_MESSAGE_LIST_HIDDEN_CHATS',
	SHOW_MESSAGE_LIST_UNREAD_CHATS: 'SHOW_MESSAGE_LIST_UNREAD_CHATS',

	// Modify conversation
	MUTE_CONVERSATION: 'MUTE_CONVERSATION',
	HIDE_CHAT: 'HIDE_CHAT',
	DELETE_CONVERSATION: 'DELETE_CONVERSATION',
	MARK_CONVERSATION_UNREAD: 'MARK_CONVERSATION_UNREAD',
	MARK_CONVERSATION_SPAM: 'MARK_CONVERSATION_SPAM',
	REPORT_CONVERSATION_SPAM_OR_ABUSE: 'REPORT_CONVERSATION_SPAM_OR_ABUSE',
	LIKE_CONVERSATION: 'LIKE_CONVERSATION',
};
